---
title: "Data import"
output: github_document
---

```{r setup}
library(tidyverse)
```


## Read in some data
### note: two ways to path, absolute path(start from the very first folder) and relative path

read in the litters dataset.

```{r}
litters_df = read_csv("./data_import_examples/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```


## take a look at the data

printing in the console

```{r}
litters_df
```

```{r}
head(litters_df)
tail(litters_df)
```

```{r}
skimr::skim(litters_df)
```


## options to read_csv

check out `read_csv()` for more information 


## other file formats

read in an excel file.

```{r}
library(readxl)
mlb_df = read_excel("./data_import_examples/mlb11.xlsx", range = "A1:F7")
mlb_df
```
 
 
 READ IN A sas file.
 
```{r}
library(haven)
pulse_df = read_sas("./data_import_examples/public_pulse_data.sas7bdat")
pulse_df
```

## comparison with base r

```{r}
litter_base = read.csv("./data_import_examples/FAS_litters.csv")
litter_readr = read_csv("./data_import_examples/FAS_litters.csv")

litter_base
litter_readr
```

 
